ClutterCollection : "{093F50FF5E4299BC}Configs/Clutter/Collections/c_collection_heather_01.conf" {
 Clutter {
  ClutterDefinition "{5482EDA3FC143EBE}" {
   ClutterConfig "{86B2058B680B876F}EBER_Materials/Clutter/Configs/EBER_c_Calluna_vulgaris_lush_02.conf"
   Occurrence 2
  }
  ClutterDefinition "{5482EDA3FCB00386}" {
   ClutterConfig "{88991F40E56E9860}EBER_Materials/Clutter/Configs/EBER_c_Calluna_vulgaris_dry_02.conf"
   Occurrence 8
  }
  ClutterDefinition "{564C9A7484825B62}" {
   ClutterConfig "{E2BEEA007E87ED77}EBER_Materials/Clutter/Configs/EBER_c_Vaccinium_myrtillus_01.conf"
  }
  ClutterDefinition "{6A629D456C349318}" {
   ClutterConfig "{CB657743BD5181C0}EBER_Materials/Clutter/Configs/EBER_c_leaves_01.conf"
   Occurrence 10
  }
  ClutterDefinition "{6A633032399D9F90}" {
   ClutterConfig "{84A76652739D816B}EBER_Materials/Clutter/Configs/EBER_coppice_deciduous_01.conf"
   Occurrence 20
  }
 }
}