ClutterCollection : "{B37FD8004BC2AF9D}Configs/Clutter/Collections/c_collection_ForestClearingCon_base.conf" {
 Clutter {
  ClutterDefinition "{59C28CE5816DA22F}" {
   ClutterConfig "{5AE9B1B0B40558F5}EBER_Materials/Clutter/Configs/EBER_c_coppice_con_large_01.conf"
   Occurrence 20
  }
 }
}