ClutterCollection : "{093F50FF5E4299BC}Configs/Clutter/Collections/c_collection_heather_01.conf" {
 Clutter {
  ClutterDefinition "{5482EDA3FC143EBE}" {
   ClutterConfig "{86B2058B680B876F}EBER_Materials/Clutter/Configs/EBER_c_Calluna_vulgaris_lush_02.conf"
   Occurrence 2
  }
  ClutterDefinition "{5482EDA3FCB00386}" {
   ClutterConfig "{88991F40E56E9860}EBER_Materials/Clutter/Configs/EBER_c_Calluna_vulgaris_dry_02.conf"
   Occurrence 8
  }
  ClutterDefinition "{564C9A7484825B62}" {
   ClutterConfig "{E2BEEA007E87ED77}EBER_Materials/Clutter/Configs/EBER_c_Vaccinium_myrtillus_01.conf"
   Occurrence 10
  }
  ClutterDefinition "{6A6330354E85F3B7}" {
   ClutterConfig "{CB657743BD5181C0}EBER_Materials/Clutter/Configs/EBER_c_leaves_01.conf"
   Occurrence 10
  }
  ClutterDefinition "{6A63303331218EA8}" {
   ClutterConfig "{38C8EBD9536DFCE9}EBER_Materials/Clutter/Configs/EBER_c_rock_debris_sharp_01_lichen.conf"
   Occurrence 30
  }
  ClutterDefinition "{6A633030FAA803BC}" {
   ClutterConfig "{FE0EF18F7B9AD0C3}EBER_Materials/Clutter/Configs/EBER_c_rock_debris_sharp_01_dense.conf"
   Occurrence 15
  }
  ClutterDefinition "{6A63303027AB8E04}" {
   ClutterConfig "{CB657743BD5181C0}EBER_Materials/Clutter/Configs/EBER_c_leaves_01.conf"
   Occurrence 25
  }
 }
}