ClutterCollection : "{093F50FF5E4299BC}Configs/Clutter/Collections/c_collection_heather_01.conf" {
 Clutter {
  ClutterDefinition "{5482EDA3FC143EBE}" {
   ClutterConfig "{6BA5CA70B8FDF604}EBER_Materials/Clutter/Configs/EBER_c_Calluna_vulgaris_lush_02_mini.conf"
   Occurrence 4
  }
  ClutterDefinition "{5482EDA3FCB00386}" {
   ClutterConfig "{00EFF0771C52733A}EBER_Materials/Clutter/Configs/EBER_c_Calluna_vulgaris_dry_02_mini.conf"
   Occurrence 5
  }
  ClutterDefinition "{564C9A7484825B62}" {
   ClutterConfig "{6F56C4475C7DEC22}EBER_Materials/Clutter/Configs/EBER_c_Vaccinium_myrtillus_01_mini.conf"
   Occurrence 4
  }
  ClutterDefinition "{6A6D3B62285DEDAD}" {
   ClutterConfig "{8FA11222C8BC33E8}EBER_Materials/Clutter/Configs/EBER_c_leaves_01_medium.conf"
   Occurrence 1
  }
  ClutterDefinition "{6A6D3B62285DED95}" {
   ClutterConfig "{84A76652739D816B}EBER_Materials/Clutter/Configs/EBER_coppice_deciduous_01.conf"
   Occurrence 2
  }
 }
}