ClutterSet : "{FA8F50C13993061D}Configs/Clutter/Sets/c_set_ForestClearingCon_01.conf" {
 DistributionMapUvScale 30
 ClutterSet {
  "{C52A03B8D3352A47}EBER_Materials/Clutter/Configs/Collection/EBER_c_collection_ForestClearingCon_base.conf"
  "{8DF9AA639C424D24}Configs/Clutter/Collections/c_collection_ForestClearingCon_branches_01.conf"
  "{3E7644655D2D3CAB}EBER_Materials/Clutter/Configs/Collection/EBER_c_collection_forestMixed_01.conf"
  "{8DF9AA639C424D24}Configs/Clutter/Collections/c_collection_ForestClearingCon_branches_01.conf"
  "{8DF9AA639C424D24}Configs/Clutter/Collections/c_collection_ForestClearingCon_branches_01.conf"
  "{8DF9AA639C424D24}Configs/Clutter/Collections/c_collection_ForestClearingCon_branches_01.conf"
  "{B0273D81B7C9C3B6}EBER_Materials/Clutter/Configs/Collection/EBER_c_collection_heather_01.conf"
 }
}